/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
/** Analizador de expresiones aritmeticas sencillas. */
package Analizador;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMERO = 5;
  /** RegularExpression Id. */
  int DECIMAL = 6;
  /** RegularExpression Id. */
  int EVALUAR = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int ELSE = 9;
  /** RegularExpression Id. */
  int CONDICION = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int DO = 12;
  /** RegularExpression Id. */
  int PCOMA = 13;
  /** RegularExpression Id. */
  int PARENI = 14;
  /** RegularExpression Id. */
  int PAREND = 15;
  /** RegularExpression Id. */
  int CORI = 16;
  /** RegularExpression Id. */
  int CORD = 17;
  /** RegularExpression Id. */
  int LLAI = 18;
  /** RegularExpression Id. */
  int LLAD = 19;
  /** RegularExpression Id. */
  int MAS = 20;
  /** RegularExpression Id. */
  int MENOS = 21;
  /** RegularExpression Id. */
  int POR = 22;
  /** RegularExpression Id. */
  int DIV = 23;
  /** RegularExpression Id. */
  int MENOR = 24;
  /** RegularExpression Id. */
  int MAYOR = 25;
  /** RegularExpression Id. */
  int IGUAL = 26;
  /** RegularExpression Id. */
  int DESIGUAL = 27;
  /** RegularExpression Id. */
  int MENORIGUAL = 28;
  /** RegularExpression Id. */
  int MAYORIGUAL = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int AND = 31;
  /** RegularExpression Id. */
  int NOT = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<NUMERO>",
    "<DECIMAL>",
    "\"Evaluar\"",
    "\"if\"",
    "\"else\"",
    "\"Condicion\"",
    "\"while\"",
    "\"do\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"OR\"",
    "\"AND\"",
    "\"NOT\"",
  };

}
